from PyQt6 import QtCore, QtGui, QtWidgets
from pathlib import Path


class Ui_EditTransactionWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(444, 368)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet(Path("src/styles/EditTransactionDialogStyle.qss").read_text())
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.EditTransaction = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditTransaction.setFont(font)
        self.EditTransaction.setObjectName("EditTransaction")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.EditTransaction)
        self.line_2 = QtWidgets.QFrame(parent=Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.line_2)
        self.EditAmount = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.EditAmount.setFont(font)
        self.EditAmount.setObjectName("EditAmount")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.EditAmount)
        self.EditAmountInput = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.EditAmountInput.setFont(font)
        self.EditAmountInput.setText("")
        self.EditAmountInput.setObjectName("EditAmountInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.EditAmountInput)
        self.EditCategory = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.EditCategory.setFont(font)
        self.EditCategory.setObjectName("EditCategory")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.EditCategory)
        self.EditCategoryInput = QtWidgets.QComboBox(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.EditCategoryInput.setFont(font)
        self.EditCategoryInput.setEditable(False)
        self.EditCategoryInput.setObjectName("EditCategoryInput")
        self.EditCategoryInput.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.EditCategoryInput)
        self.EditDescription = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.EditDescription.setFont(font)
        self.EditDescription.setObjectName("EditDescription")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.EditDescription)
        self.EditDescriptionInput = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.EditDescriptionInput.setFont(font)
        self.EditDescriptionInput.setObjectName("EditDescriptionInput")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.EditDescriptionInput)
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.line)
        self.Buttons = QtWidgets.QWidget(parent=Dialog)
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.CancelButton = QtWidgets.QPushButton(parent=self.Buttons)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CancelButton.setFont(font)
        self.CancelButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.SaveButton = QtWidgets.QPushButton(parent=self.Buttons)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SaveButton.setFont(font)
        self.SaveButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Buttons)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.EditTransaction.setText(_translate("Dialog", "Edit Transaction"))
        self.EditAmount.setText(_translate("Dialog", "Amount"))
        self.EditAmountInput.setPlaceholderText(_translate("Dialog", "0.00"))
        self.EditCategory.setText(_translate("Dialog", "Category"))
        self.EditCategoryInput.setCurrentText(_translate("Dialog", "New Item"))
        self.EditCategoryInput.setItemText(0, _translate("Dialog", "New Item"))
        self.EditDescription.setText(_translate("Dialog", "Description"))
        self.EditDescriptionInput.setPlaceholderText(_translate("Dialog", "What\'s this transaction for?"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
        self.SaveButton.setText(_translate("Dialog", "Save Transaction"))
