from PyQt6 import QtCore, QtGui, QtWidgets
from pathlib import Path


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(444, 442)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet(Path("src/styles/TransactionDialogStyle.qss").read_text())
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.NewTransaction = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NewTransaction.setFont(font)
        self.NewTransaction.setObjectName("NewTransaction")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.NewTransaction)
        self.line_2 = QtWidgets.QFrame(parent=Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.line_2)
        self.Amount = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Amount.setFont(font)
        self.Amount.setObjectName("Amount")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Amount)
        self.AmountInput = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.AmountInput.setFont(font)
        self.AmountInput.setText("")
        self.AmountInput.setObjectName("AmountInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.AmountInput)
        self.Category = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Category.setFont(font)
        self.Category.setObjectName("Category")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Category)
        self.CategoryInput = QtWidgets.QComboBox(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.CategoryInput.setFont(font)
        self.CategoryInput.setEditable(False)
        self.CategoryInput.setObjectName("CategoryInput")
        self.CategoryInput.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.CategoryInput)
        self.Date = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Date.setFont(font)
        self.Date.setObjectName("Date")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Date)
        self.DateInput = QtWidgets.QDateEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateInput.setFont(font)
        self.DateInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.DateInput.setCalendarPopup(True)
        self.DateInput.setDate(QtCore.QDate(2025, 5, 7))
        self.DateInput.setObjectName("DateInput")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.DateInput)
        self.Description = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Description.setFont(font)
        self.Description.setObjectName("Description")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Description)
        self.DescriptionInput = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DescriptionInput.setFont(font)
        self.DescriptionInput.setObjectName("DescriptionInput")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.DescriptionInput)
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.line)
        self.Buttons = QtWidgets.QWidget(parent=Dialog)
        self.Buttons.setObjectName("Buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.CancelButton = QtWidgets.QPushButton(parent=self.Buttons)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CancelButton.setFont(font)
        self.CancelButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.SaveButton = QtWidgets.QPushButton(parent=self.Buttons)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SaveButton.setFont(font)
        self.SaveButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Buttons)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.NewTransaction.setText(_translate("Dialog", "New Transaction"))
        self.Amount.setText(_translate("Dialog", "Amount"))
        self.AmountInput.setPlaceholderText(_translate("Dialog", "0.00"))
        self.Category.setText(_translate("Dialog", "Category"))
        self.CategoryInput.setCurrentText(_translate("Dialog", "New Item"))
        self.CategoryInput.setItemText(0, _translate("Dialog", "New Item"))
        self.Date.setText(_translate("Dialog", "Date"))
        self.DateInput.setDisplayFormat(_translate("Dialog", "MM/dd/yyyy"))
        self.Description.setText(_translate("Dialog", "Description"))
        self.DescriptionInput.setPlaceholderText(_translate("Dialog", "What\'s this transaction for?"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
        self.SaveButton.setText(_translate("Dialog", "Save Transaction"))
